/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_callback_DataProvider */

#ifndef _Included_com_example_callback_DataProvider
#define _Included_com_example_callback_DataProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_callback_DataProvider
 * Method:    method1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_callback_DataProvider_method1
  (JNIEnv *, jobject);

/*
 * Class:     com_example_callback_DataProvider
 * Method:    method2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_callback_DataProvider_method2
  (JNIEnv *, jobject);

/*
 * Class:     com_example_callback_DataProvider
 * Method:    method3
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_callback_DataProvider_method3
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
